[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["William Ingersoll <wfingersoll@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flask = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
